### ISSUE TITLE
Create python tools for pre/post-processing

### ISSUE THREAD

**Issue by jsauer-NCAR** [NCAR/FastEddy-model#14]
## Describe the Enhancement ##
Provide python scripts developed for various pre/post-processing tasks 

- Create a Tools directory in the repository
- Provide the binary-to-netcdf converter
- Provide ...
- Provide ...

### Time Estimate ###
1-3 days

### Relevant Deadlines ###
Should be a part of the v2.0 release (June 2024)

### Assignee ###
- [x] Assign this Task to the appropriate person

### Labels ###
- [x] Select **pillar**
- [x] Select **priority**
- [x] Select **requestor(s)**

**Comment by jprestop** [comment]
Closing with PR #47
