### ISSUE TITLE
Add documentation notes to the release to describe fixes/enhancements/extensions

### ISSUE THREAD

**Issue by domingom** [NCAR/FastEddy-model#37]
## Describe the Task ##
Add documentation notes to the release to describe fixes/enhancements/extensions

### Time Estimate ###
~1 day of work.

### Relevant Deadlines ###
July release.

### New Parameters ###
*Define any new parameters here or state NONE.*

### Technical References ###
*List relevant technical references here or state NONE.*

### Assignee ###
- [ ] Assign this Task to the appropriate person

### Labels ###
- [ ] Select **pillar**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

**Comment by jprestop** [comment]
Closed with PR #49
